### ISSUE TITLE
AXSize and AXPosition attributes fail with : AXValueRef object is not iterable 

### ISSUE THREAD

**Issue by chaps** [pyatom/pyatom#162]
The  _CFAttributeToPyObject method under https://github.com/pyatom/pyatom/blob/master/atomac/_a11y.py
fails when trying to cast an AXValue to a tuple type object.

This happens on both kAXValueCGSizeType and kAXValueCGPointType AXValue Types, when the methods : AXSize or AXPosition are referenced

One can use the steps under the usage section and call AXSize or AXPosition in order to reproduce.

```
import atomac
atomac.launchAppByBundleId('com.apple.Automator')
automator = atomac.getAppRefByBundleId('com.apple.Automator')
window = automator.windows()[0]

sheet = window.sheets()[0]
close = sheet.buttons('Close')[0]
print(close.getAttributes())

close.AXPosition

```

Continuing with the previous code,  the _getattribute method under https://github.com/pyatom/pyatom/blob/master/atomac/_a11y.py inits an AXUIElementCopyAttributeValue object,  which displays the position coordinates correctly when printed.:

`
err, attrValue = AXUIElementCopyAttributeValue(close.ref, attr, None)
print(attrValue)
`

**Comment by daveenguyen** [comment]
👍 Great find @chaps !
Can you include copypaste of the exceptions/errors you see and what the expected correct values are?
I'll try out your steps when I am able to.

For now, this should be what the previous implementation was to convert those values to tuple. https://github.com/pyatom/pyatom/blob/7a0e8f6f8fb2161f0b50750ccc32ba3700b099ea/atomac/_a11y/conversion.c#L110

My casting to tuple was definitely not the correct way. Let me know if you have any attempts :)

**Comment by daveenguyen** [comment]
Looked into it a bit and found issues with `AXValueGetValue` :(
#163 for more details.

@chaps try the changes in #163 to see if it works for you.

**Comment by chaps** [comment]
Hey @daveenguyen  thanks a lot this works fine , 
tested over python 2.7.15 I'll be checking tomorrow on python 3.

I was actually trying to call `AXValueGetValue ` and ended also using the string repr.  like :
`
def get_position_tuple(axuielement):
    #
    err, value = AXUIElementCopyAttributeValue(axuielement.ref, "AXPosition", None)
    position_re = re.compile("x:(\d+\.\d+) y:(\d+\.\d+)")
    return map(float, position_re.search(str(value)).groups())


def get_size_tuple(axuielement):
    #
    err, value = AXUIElementCopyAttributeValue(axuielement.ref, "AXSize", None)
    size_re = re.compile("w:(\d+\.\d+) h:(\d+\.\d+)")
    return map(float, size_re.search(str(value)).groups())
`

I'm not very familiar with the `ApplicationServices`/ `pyobjc` handlers , do you think there's someway to access the values the object is using in the string repr. in order to avoid  parsing the string?

**Comment by daveenguyen** [comment]
I'm also parsing the string repr in my PR.
Not too familiar with pobjc code as well. 
I dug into pyobjc code a bit and found it's using objective-c "description" to get the string repr.

https://bitbucket.org/ronaldoussoren/pyobjc/src/54a895eefa1dc5d7e6cdc42cbdac0d2b0e7eb0e6/pyobjc-core/Modules/objc/objc-object.m#lines-99:112

For example
```python
>>> size.description()
'<AXValue 0x7fb2c3100f40> {value = w:1440.000000 h:804.000000 type = kAXValueCGSizeType}'
```

I also created an issue to hopefully get some ideas
https://bitbucket.org/ronaldoussoren/pyobjc/issues/260/segfault-when-calling-axvaluegetvalue

**Comment by chaps** [comment]
@daveenguyen Got that , are you ok with me closing this issue until https://github.com/pyatom/pyatom/pull/163 gets Pulled?

**Comment by daveenguyen** [comment]
@chaps Either way works for me. Don't know if changes will get pulled in.
I've updated #163 using Foundation's NSPoint,NSSize,NSRange FromString 😄 
https://developer.apple.com/documentation/foundation/1391112-nssizefromstring?language=objc

**Comment by daveenguyen** [comment]
I reference pyobjc docs and apple's docs.
https://pyobjc.readthedocs.io/

Somewhere it said `CGSize` and `NSSize` are pretty much alias and that led me to find `NSSizeFromString`.

I should've looked deeper to find `CGSizeFromString` rather than the `NSSizeFromString` because
the AXValue's type is actually `CG` (`kAXValueCGSizeType`)

`'<AXValue 0x7fb2c3100f40> {value = w:1440.000000 h:804.000000 type = kAXValueCGSizeType}'`

**Comment by chaps** [comment]
Closing this as https://github.com/pyatom/pyatom/pull/163 has been merged . :) 
Thanks again for the info @daveenguyen  💯
