### ISSUE TITLE
Is 10.7.3 supported?

### ISSUE THREAD

**Issue by aivaturi** [pyatom/pyatom#25]
I'm trying out pyatom on 10.7.3 & things don't seem to be working correctly. Here is an e.g.

``` python
>>> atomac.launchAppByBundleId('com.apple.Automator')
>>> automator = atomac.getAppRefByBundleId('com.apple.Automator')
>>> automator
<atomac.AXClasses.NativeUIElement <No role!> ''>
```

The first statement launches the automator but for some reason I get `<No role!>` instead of "AXApplication u'Automator'". Is there something that I'm missing installation/configuration wise?

**Comment by suresh1227** [comment]
Hi 

sheet = window.sheets()[0] 

returns Error.

IndexError: list index out of range

but there is an Element.

**Comment by SharonAndroid** [comment]
I have turned accessibility on, but still I got this error 'No role', anyone can help me?

**Comment by sbroberg** [comment]
@SharonAndroid : I struggled with this problem myself today.  The solution (at least on 10.12, and I assume on the earlier versions) is that you need to add the application that is launching your python process (Typically "Terminal") to System Preferences->Security & Privacy->Accessibility.  If you're running from an IDE like PyCharm, Eclipse, etc., you'll need to add those as well.

**Comment by suresh1227** [comment]
yes you need to add
